### ISSUE TITLE
Decide on standard configuration for Beckhoff TwinCAT/PLC projects

### ISSUE THREAD

**Issue by klauer** [pcdshub/pre-commit-hooks#2]
* Can include actual check scripts here in this repository, or refer to pcds-ci-helpers scripts?

**Comment by ZLLentz** [comment]
I think ci-helpers should draw from here, rather than the other way around so we can have one source for the group of them

Either way: we'll want to throw on some custom ones for TwinCAT projects, we've discussed in the past here: https://github.com/pcdshub/pcds-ci-helpers/issues/9

Mostly just targeted xml beautification, banning leading tabs, catching the lineIds...

**Comment by ZLLentz** [comment]
Hmm, I think I should have started in this repo instead of in ci-helpers this week... It seems like doing the checks before pushing to github would be more useful than waiting for the travis to run. But at least the travis checks for people who didn't configure their pre-commit-hooks.

In order of priority, I want to set this up to:
- Beautify the .tmc and NC/CoE xml files
- find and replace leading tabs
- eliminate LineId lines

And then I'll just grab all the pre-commit-hooks standards that seem good, e.g.
- trim trailing whitespace

I'll look around for hooks that others have written before diving in to writing our own.

**Comment by klauer** [comment]
Sounds good to me. I wouldn't doubt there's already an XML beautifier one that could be used in place of rolling our own (or using what I had whipped up months ago)

**Comment by ZLLentz** [comment]
Finding the one you whipped up counts as looking around for hooks that others have written :+1:

We'll probably need to do something ourselves for these anyway since they need to target specific odd filetypes

**Comment by ZLLentz** [comment]
klauer's pre-commit gist for reference while working on this: https://gist.github.com/klauer/a1489e408042a95ed9e804e37e7832c2
